<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="template_model" nsURI="http://www.se.fudan.edu.cn/clonepedia"
    nsPrefix="clonepedia.model.template.graphic">
  <eClassifiers xsi:type="ecore:EClass" name="TemplateGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateMethodGroups" upperBound="-1"
        eType="#//TMG" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateFeatureGroups"
        upperBound="-1" eType="#//TFG" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calleeMethods" upperBound="-1"
        eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerType" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//TemplateGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComplete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportingElements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcFolder" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variationType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerClasses" upperBound="-1"
        eType="#//Class" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superInterfaces" upperBound="-1"
        eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMG">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="2"
        upperBound="-1" eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//TemplateGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFG">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMGs" lowerBound="1" upperBound="-1"
        eType="#//TMG" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//TemplateGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComplete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variationType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerMethod" lowerBound="1"
        eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calleeMethod" lowerBound="1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implement" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        upperBound="-1" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendClass" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subClass" lowerBound="1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" lowerBound="1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendInterface" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subInterface" lowerBound="1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superInterface" lowerBound="1"
        upperBound="-1" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerType" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
